name: env
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_2
  - aiodns=3.5.0=py313hca03da5_1
  - aiohappyeyeballs=2.6.1=py313hca03da5_0
  - aiohttp=3.13.2=py313haa24f5a_0
  - aiosignal=1.4.0=py313hca03da5_0
  - alembic=1.17.2=py313hca03da5_0
  - altair=5.5.0=py313hca03da5_0
  - annotated-doc=0.0.4=py313hca03da5_0
  - annotated-types=0.6.0=py313hca03da5_1
  - anyio=4.10.0=py313hca03da5_0
  - aom=3.6.0=h313beb8_0
  - appnope=0.1.4=py313hca03da5_0
  - arrow-cpp=21.0.0=h9e9184e_1
  - asttokens=3.0.0=py313hca03da5_0
  - attrs=25.4.0=py313hca03da5_2
  - aws-c-auth=0.9.0=h79febb2_2
  - aws-c-cal=0.9.2=h79febb2_1
  - aws-c-common=0.12.4=h79febb2_0
  - aws-c-compression=0.3.1=h79febb2_2
  - aws-c-event-stream=0.5.6=h79febb2_0
  - aws-c-http=0.10.4=h79febb2_0
  - aws-c-io=0.21.4=h79febb2_0
  - aws-c-mqtt=0.13.3=h387b88a_0
  - aws-c-s3=0.8.7=h79febb2_0
  - aws-c-sdkutils=0.2.4=h79febb2_1
  - aws-checksums=0.2.7=h79febb2_1
  - aws-crt-cpp=0.34.0=hee39554_0
  - aws-sdk-cpp=1.11.638=h35fa3df_0
  - bcrypt=5.0.0=py313h931abed_0
  - beautifulsoup4=4.13.5=py313hca03da5_0
  - blas=1.0=openblas
  - blinker=1.9.0=py313hca03da5_1
  - bottleneck=1.4.2=py313ha35b7ea_0
  - brotlicffi=1.1.0.0=py313h50f4ffc_0
  - bs4=4.13.5=py39hd3eb1b0_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cachetools=5.5.1=py313hca03da5_0
  - cairo=1.18.4=h191e429_0
  - catboost=1.2.8=py313h167317f_0
  - certifi=2025.11.12=py313hca03da5_0
  - cffi=2.0.0=py313h73c2a22_1
  - charset-normalizer=3.4.4=py313hca03da5_0
  - click=8.2.1=py313hca03da5_0
  - cloudpickle=3.1.1=py313hca03da5_0
  - comm=0.2.3=py313hca03da5_0
  - contourpy=1.3.1=py313h48ca7d4_0
  - cryptography=45.0.7=py313h83bfa8c_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - databricks-sdk=0.63.0=py313hca03da5_0
  - datasets=3.3.2=py313hca03da5_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py313h50f4ffc_1
  - decorator=5.2.1=py313hca03da5_0
  - dill=0.3.8=py313hca03da5_0
  - docker-py=7.1.0=py313hca03da5_0
  - executing=2.2.1=py313hca03da5_0
  - expat=2.7.1=h313beb8_0
  - fastapi=0.121.1=py313hf834670_0
  - filelock=3.20.0=py313hca03da5_0
  - flask=3.1.2=py313hca03da5_0
  - flask-cors=6.0.1=pyhe01879c_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h29935d0_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.60.1=py313h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - frozenlist=1.8.0=py313h50f4ffc_0
  - gdk-pixbuf=2.42.10=h969f7ef_2
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=h313beb8_1
  - giflib=5.2.2=h80987f9_0
  - gitdb=4.0.12=py313hca03da5_0
  - gitpython=3.1.45=py313hca03da5_0
  - glib=2.84.2=hc880cf1_0
  - glib-tools=2.84.2=hc880cf1_0
  - glog=0.5.0=h313beb8_1
  - google-auth=2.38.0=py313hca03da5_1
  - graphene=3.4.3=py313hca03da5_0
  - graphite2=1.3.14=hc377ac9_1
  - graphql-core=3.2.6=py313hca03da5_0
  - graphql-relay=3.2.0=py313hca03da5_1
  - graphviz=2.50.0=hdc6c5f9_2
  - greenlet=3.2.4=py313h0962b89_0
  - gts=0.7.6=hde733a8_3
  - gunicorn=23.0.0=py313hca03da5_1
  - h11=0.16.0=py313hca03da5_1
  - harfbuzz=10.2.0=he637ebf_1
  - hf-xet=1.1.8=py313h8cd5084_0
  - huey=2.5.4=pyhcf101f3_0
  - huggingface_hub=0.34.4=py313hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.11=py313hca03da5_0
  - importlib-metadata=8.7.0=py313hca03da5_0
  - invoke=2.2.0=py313hca03da5_0
  - ipykernel=6.31.0=py313h7eb115d_0
  - ipython=9.7.0=py313hca03da5_0
  - ipython_pygments_lexers=1.1.1=py313hca03da5_0
  - itsdangerous=2.2.0=py313hca03da5_0
  - jedi=0.19.2=py313hca03da5_0
  - jinja2=3.1.6=py313hca03da5_0
  - joblib=1.5.2=py313hca03da5_0
  - jpeg=9f=h2f69dba_0
  - jsonschema=4.25.0=py313hca03da5_1
  - jsonschema-specifications=2025.9.1=py313hca03da5_0
  - jupyter_client=8.6.3=py313hca03da5_1
  - jupyter_core=5.8.1=py313hca03da5_0
  - kiwisolver=1.4.8=py313h313beb8_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libavif=1.1.1=h80987f9_0
  - libboost=1.88.0=hb389264_0
  - libbrotlicommon=1.0.9=h80987f9_9
  - libbrotlidec=1.0.9=h80987f9_9
  - libbrotlienc=1.0.9=h80987f9_9
  - libcurl=8.16.0=h01d3526_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libffi=3.4.4=hca03da5_1
  - libgd=2.3.3=hd3b0a14_4
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.2=hdc2269c_0
  - libgrpc=1.71.0=h62f6fdd_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.30=hf2bb037_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=5.29.3=h14f15fd_1
  - libre2-11=2024.07.02=h313beb8_0
  - librsvg=2.56.3=h38920c8_2
  - libsodium=1.0.20=h897f8a9_0
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.22.0=hbe873a3_0
  - libtiff=4.7.0=h91aec0a_0
  - libtool=2.4.7=h313beb8_0
  - libunistring=1.3=h1799b2a_0
  - libuv=1.48.0=h80987f9_0
  - libwebp=1.3.2=hf40cdb4_1
  - libwebp-base=1.3.2=h80987f9_1
  - libxgboost=3.0.1=h313beb8_0
  - libxml2=2.13.8=h0b34f26_0
  - libzlib=1.3.1=h5f15de7_0
  - lightgbm=4.6.0=py313h313beb8_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - mako=1.3.10=py313hca03da5_0
  - markdown=3.8=py313hca03da5_0
  - markupsafe=3.0.2=py313h80987f9_0
  - matplotlib=3.10.6=py313hca03da5_0
  - matplotlib-base=3.10.6=py313h8596600_0
  - matplotlib-inline=0.2.1=py313hca03da5_0
  - mlflow=3.6.0=pyh707e725_0
  - mlflow-skinny=3.6.0=pyh707e725_0
  - mlflow-ui=3.6.0=pyh707e725_0
  - multidict=6.7.0=py313h254cc4a_0
  - multiprocess=0.70.15=py313hca03da5_0
  - narwhals=2.7.0=py313hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py313hca03da5_0
  - nltk=3.9.1=py313h0ef513f_0
  - nspr=4.37=hd3a7ab8_0
  - nss=3.117=hfbaeeee_0
  - numexpr=2.11.0=py313hf08b1b5_1
  - numpy=2.3.3=py313h4bb6f22_1
  - numpy-base=2.3.3=py313h23175f9_1
  - openjpeg=2.5.2=hba36e21_1
  - openssl=3.6.0=h5503f6c_0
  - opentelemetry-api=1.38.0=py313hca03da5_0
  - opentelemetry-proto=1.39.0=pyhd8ed1ab_0
  - opentelemetry-sdk=1.38.0=py313hca03da5_0
  - opentelemetry-semantic-conventions=0.59b0=py313hca03da5_0
  - orc=2.2.0=hec253e6_0
  - packaging=25.0=py313hca03da5_1
  - pandas=2.3.3=py313h6316d20_0
  - pango=1.50.7=hf2328af_2
  - paramiko=4.0.0=py313hca03da5_0
  - parso=0.8.5=py313hca03da5_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.9.0=py313hca03da5_1
  - pillow=11.3.0=py313h6dd570d_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.5.0=py313hca03da5_0
  - plotly=6.3.0=py313h7eb115d_0
  - poppler=24.09.0=h10a2f5c_4
  - poppler-data=0.4.12=hca03da5_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=py313hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.3.1=py313h80987f9_0
  - protobuf=5.29.3=py313h514c7bf_0
  - psutil=7.0.0=py313haa24f5a_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py313hca03da5_0
  - py-xgboost=3.0.1=py313hca03da5_0
  - pyarrow=21.0.0=py313h6316d20_0
  - pyasn1=0.6.1=py313hca03da5_0
  - pyasn1-modules=0.4.2=py313hca03da5_0
  - pycares=4.10.0=py313h091efcb_0
  - pycparser=2.23=py313hca03da5_0
  - pydantic=2.12.4=py313hca03da5_0
  - pydantic-core=2.41.5=py313h931abed_1
  - pydeck=0.9.1=py313hca03da5_0
  - pygments=2.19.2=py313hca03da5_0
  - pynacl=1.6.0=py313h8ceae07_0
  - pyopenssl=25.3.0=py313hc20e4cf_0
  - pyparsing=3.2.0=py313hca03da5_0
  - pysocks=1.7.1=py313hca03da5_1
  - python=3.13.9=hc7d8306_100_cp313
  - python-dateutil=2.9.0post0=py313hca03da5_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-graphviz=0.20.1=py313hca03da5_1
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py313h80987f9_0
  - python_abi=3.13=1_cp313
  - pytz=2025.2=py313hca03da5_0
  - pyyaml=6.0.3=py313h091b9d3_0
  - pyzmq=27.1.0=py313h5a8c52c_1
  - querystring_parser=1.2.4=pyhd8ed1ab_2
  - re2=2024.07.02=h48ca7d4_0
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=py313hca03da5_0
  - regex=2025.9.1=py313h254cc4a_0
  - requests=2.32.5=py313hca03da5_1
  - rpds-py=0.28.0=py313h931abed_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - safetensors=0.6.2=py313h931abed_0
  - scikit-learn=1.7.2=py313h6316d20_0
  - scipy=1.16.3=py313h08a1045_0
  - seaborn=0.13.2=py313hca03da5_3
  - setuptools=80.9.0=py313hca03da5_0
  - six=1.17.0=py313hca03da5_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=h313beb8_0
  - sniffio=1.3.1=py313hca03da5_0
  - soupsieve=2.5=py313hca03da5_0
  - sqlalchemy=2.0.43=py313h9945a3e_0
  - sqlite=3.50.2=h79febb2_1
  - sqlparse=0.5.3=py313hca03da5_0
  - stack_data=0.6.3=py313hca03da5_0
  - starlette=0.47.3=py313hca03da5_0
  - streamlit=1.52.0=pyhd8ed1ab_0
  - tenacity=9.1.2=py313hca03da5_0
  - threadpoolctl=3.5.0=py313h7eb115d_0
  - tk=8.6.15=hcd8a7d5_0
  - tokenizers=0.22.1=py313h99e1e97_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.5.1=py313h80987f9_0
  - tqdm=4.67.1=py313h7eb115d_0
  - traitlets=5.14.3=py313hca03da5_0
  - transformers=4.57.3=pyhd8ed1ab_0
  - typing-extensions=4.15.0=py313hca03da5_0
  - typing-inspection=0.4.2=py313hca03da5_0
  - typing_extensions=4.15.0=py313hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py313hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - uvicorn=0.35.0=py313hca03da5_0
  - uvloop=0.22.1=py313h8e34c70_1
  - watchdog=6.0.0=py313h254cc4a_0
  - wcwidth=0.2.13=py313hca03da5_0
  - websocket-client=1.8.0=py313hca03da5_0
  - werkzeug=3.1.3=py313hca03da5_0
  - wheel=0.45.1=py313hca03da5_0
  - xgboost=3.0.1=py313hca03da5_0
  - xxhash=0.8.0=h1a28f6b_3
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.22.0=py313haa24f5a_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zipp=3.23.0=py313hca03da5_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - automodel==0.5.9
      - fsspec==2025.12.0
      - mpmath==1.3.0
      - networkx==3.6
      - plumbum==1.10.0
      - rpyc==6.0.2
      - sympy==1.14.0
      - torch==2.9.1
prefix: /opt/anaconda3/envs/env
